### ISSUE TITLE
PCA should do the eigenvalue decomposition of the mean centered COVARIANCE matrix

### ISSUE THREAD

**Issue by manugarri** [eriklindernoren/NapkinML#1]
not just the svd of the mean-centered matrix.

**Comment by eriklindernoren** [comment]
It's possible to do PCA both by SVD and eigenvalue decomposition of the covariance matrix. Here's a reference: http://www2.imm.dtu.dk/pubdb/views/edoc_download.php/4000/pdf/imm4000

**Comment by manugarri** [comment]
What you are doing is just SVD of the mean centered data, even though there is a relationship between components of mean centered data and eigenvalues, why not calling it SVD instead?. After all , all you are doing is calling linalg.svd. 

The reason i am saying this is that I assume the goal of this library is educational (if not why creating wrappers for numpy functions?), and not implementing the educational approach of PCA (check any educational resource that explains PCA  on a simple way like [this](https://www.youtube.com/watch?v=_UVHneBUBW0&t=581s), or [this](https://deeplearning4j.org/eigenvector#principal) ) , actually harms the education part of the library.

**Comment by eriklindernoren** [comment]
Well, no that's not all that's being done... SVD is a more numerically stable way of doing PCA. If you look at other libraries most of them will use SVD instead of explicitly calculating the covariance matrix (http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html).

Here's a good explanation: https://math.stackexchange.com/questions/3869/what-is-the-intuitive-relationship-between-svd-and-pca

Also section VI in: https://arxiv.org/pdf/1404.1100.pdf

**Comment by manugarri** [comment]
@eriklindernoren There are many ways of doing the decomposition part of PCA, you could do spectral decomposition instead of SVD.  SVD by itself is another common method of dimensionality reduction all by itself (quite more useful and with many other applications than just  dimensionality reduction)

Anyway, it is your library, I just thought it would make more sense to provide a better implementation for people willing to check the code and learn what is going on (not just calling (the numpy implementation))
